--- arch/arm/dts/Makefile
+++ arch/arm/dts/Makefile
@@ -652,7 +652,7 @@ dtb-$(CONFIG_MACH_SUN8I_V3S) += \
 	sun8i-v3-sl631-imx179.dtb \
 	sun8i-v3s-licheepi-zero.dtb
 dtb-$(CONFIG_MACH_SUN8I_R528) += \
-	sun8i-t113s-mangopi-mq-r-t113.dtb
+	sun8i-t113s-saxo.dtb
 dtb-$(CONFIG_MACH_SUN50I_H5) += \
 	sun50i-h5-bananapi-m2-plus.dtb \
 	sun50i-h5-emlid-neutis-n5-devboard.dtb \
